### ISSUE TITLE
61115 - [Newsroom] Common Modules - Button - Missing tooltips

### ISSUE THREAD

**Issue by michellemagtanong** [hlxsites/accenture-newsroom#79] opened 2023-09-14 09:47 UTC
**Priority 3 - Medium**

**Description of the issue:** Missing tooltips

**Steps to Reproduce:** 

1. Open the urls(s):
**Adobe Franklin migrated page:**
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory

**Legacy newsroom page:**
https://newsroom.accenture.com/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture.htm
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm

2. Check for the Button in the share module
3. Hover on the Button to check user interactions.

**Expected Result:**
Should have tooltips when hovering the button
![image](https://github.com/hlxsites/accenture-newsroom/assets/144991351/d506d1c2-3d23-44e6-8b38-84d6a1a0bcf6)

**Actual Result:**
No tooltips
![image](https://github.com/hlxsites/accenture-newsroom/assets/144991351/f5aa146b-b250-4cfe-9b9f-e4e3f8fc1cdd)

AZDO Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/61115
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by ravkiran** [comment] 2023-09-19 22:26
duplicate of #79, fixed in #112

**Closed by ravkiran** 2023-09-19 22:26 UTC
