### ISSUE TITLE
332614 - [Newsroom][Content Migration] CTA Button not migrated/missing in newsroom article pages

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#400] opened 2023-10-27 17:25 UTC
Description: CTA Button "Click to Download" does not exist on migrated pages in newsroom.

Legacy: https://newsroom.accenture.com/news/accenture-reports-very-strong-third-quarter-results.htm
Migrated: https://tempnewsroom.accenture.com/news/2022/accenture-reports-very-strong-third-quarter-results

Expected: CTA Button is visible in article pages
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7c6c999e-d90b-4dbe-8c76-5f6e223236b5)

Actual: CTA Button is missing
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/b3aef28a-9169-48eb-b23d-b89c8e8e464a)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/332614
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment] 2023-10-27 18:07
Duplicate of https://github.com/hlxsites/accenture-newsroom/issues/380. closing this issue and continue the other one.

**Closed by amol-anand** 2023-10-27 18:07 UTC
Labels: bug, High Priority
