### ISSUE TITLE
74156 - [Newsroom] Share_Download press release CTA_"Convert to PDF" tool tip is missing

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#99] opened 2023-09-18 07:02 UTC
**Severity 3 - Medium**

**Steps to reproduce:**
1. Consider the legacy page: https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory
2. Hover on the "download press release " CTA button

**Expected Result:** On hover of the press release CTA, Convert to PDF tool tip is displayed
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/5adef51a-feb9-47aa-9897-7a2f9fa21dca)

**Actual Result:** Tool tip is missing on the 'download press release' CTA
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/a789a9e7-1cbf-4b1a-b6c7-597349f1f58a)

Azdo Link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/74156
CC: @ravkiran @amol-anand  @raymond-h-dev

**Comment by ravkiran** [comment] 2023-09-19 22:24
duplicate of https://github.com/hlxsites/accenture-newsroom/issues/79, fixed in https://github.com/hlxsites/accenture-newsroom/pull/112

**Closed by ravkiran** 2023-09-19 22:24 UTC
